/* ----------------------------------------------------------------------------
 *         ATMEL Microcontroller Software Support 
 * ----------------------------------------------------------------------------
 * Copyright (c) 2008, Atmel Corporation
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the disclaimer below.
 *
 * Atmel's name may not be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * DISCLAIMER: THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * ----------------------------------------------------------------------------
 */

//------------------------------------------------------------------------------
/// \dir "LCD Slideshow Project"
///
/// !!!Purpose
///
/// This application displays a slideshow on the on-board LCD screen. 
/// Images (in BMP format) can be added to the slideshow by sending them through 
/// a USB virtual COM port created by the program. 
///
/// !See
/// - lcd: LCD driver
/// - rtt: Real time timer driver
/// - usb: USB Framework, USB CDC driver and UDP interface driver
///    - "AT91 USB device framework"
///       - "USBD API"
///    - "cdc-serial"
///
/// !!!Requirements
///
/// This package can be used with all Atmel evaluation kits that have both
/// LCD and UDP interface.
///
/// !!!Description
///
/// When executed, the application waits for incoming BMP files over the USB. 
/// When at least one file has been received, a slideshow animation begins. 
/// It shows each image during two seconds before switching to the next one. 
///
/// This example uses the USB to create a virtual COM port on the host. 
/// This enables easy transfer of image files, since any terminal application
/// can be used for that. #Images must be transferred as a raw stream of data,
/// i.e. without using any protocol such as XMODEM.#
///
/// !!!Usage
///
/// -# Build the application. 
/// -# Optionally, the DBGU port of the board can be connected to the PC and 
/// opened using a terminal application. Debug traces generated by the software
/// will be available that way. 
///     - Settings: 115200 bauds, 8 bits, 1 stop bit, no parity, no flow control. 
/// -# Download the application inside the microcontroller memory and run it. 
/// Please refer to the 
///    <a href="http://www.atmel.com/dyn/resources/prod_documents/doc6224.pdf">
///    SAM-BA User Guide</a>, the 
///    <a href="http://www.atmel.com/dyn/resources/prod_documents/doc6310.pdf">
///    GNU-Based Software Development</a>, application note or to the 
///    <a href="http://www.iar.se/website1/1.0.1.0/78/1/index.php?">
///    IAR EWARM User Guide</a>, depending on your chosen solution. 
/// -# The following message should be displayed on the DBGU: 
///     \code
///     -- LCD Slideshow Project xxx --
///     -- AT91xxxxxx-xx
///     -- Compiled: xxx xx xxxx xx:xx:xx --
///     \endcode
/// -# Connect the USB cable between the evaluation board and the computer. On
/// Microsoft Windows, a driver may be required when the device is plugged for
/// the first time. Point the installation wizard to the 
/// at91lib/usb/device/cdc-serial/drv directory and select the .inf file  
/// located inside it.
/// -# After the device is enumerated properly by the host, a virtual COM port
/// will be created. The application will then wait for BMP files to be sent.
/// This is notified by the message below: 
///        \code
///        Ready to receive BMP file #0. 
///        \endcode
/// -# Open the virtual COM port using a terminal application. 
/// -# Send a BMP image using the terminal to add it to the current slideshow. 
/// The BMP must have the following format: 
///     - Width: 240 pixels 
///     - Height: 320 pixels 
///     - Color resolution: 8- or 24-bits 
/// \n
/// \n
/// #Note 1#: depending on the terminal application, it may be necessary to  
/// select a "binary" transfer mode for the correct data to be sent. 
/// \n
/// #Note 2#: several terminal applications, such as HyperTerminal, use a very 
/// inefficient packet size when transferring data. This may result in a slow 
/// data rate.
///
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
/// \unit
///
/// !Purpose
///
/// This file contains all the specific code for the 
/// lcd-slideshow-project.
///
/// !Contents
/// The code can be roughly broken down as follows:
///    - Configuration functions
///    - Initialization functions
///    - BMP data receive functions
///    - RTT interrupt handle
///    - The main function, which implements the program behavior
///       - Configure pins
///       - Initialize LCD
///       - Configure RTT and initialize the serial driver
///       - Start receiving data on the USB
///       - When at least one file has been received, a slideshow animation begins
///
/// Please refer to the list of functions in the #Overview# tab of this unit
/// for more detailed information.
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//         Headers
//------------------------------------------------------------------------------

#include <board.h>
#include <board_memories.h>
#include <pio/pio_it.h>
#include <irq/irq.h>
#include <dbgu/dbgu.h>
#include <lcd/lcd.h>
#include <rtt/rtt.h>
#include <utility/bmp.h>
#include <utility/trace.h>
#include <usb/device/core/USBD.h>
#include <usb/device/cdc-serial/CDCDSerialDriver.h>
#include <usb/device/cdc-serial/CDCDSerialDriverDescriptors.h>

#include <string.h>

//------------------------------------------------------------------------------
//         Internal constants
//------------------------------------------------------------------------------

#if defined(PINS_DDRAM)
#undef IMAGE_BUF_BASE_ADDR
#define IMAGE_BUF_BASE_ADDR AT91C_DDR2
#endif

#if defined(PINS_SDRAM)
#undef IMAGE_BUF_BASE_ADDR
#define IMAGE_BUF_BASE_ADDR AT91C_EBI_SDRAM
#endif

/// Custom INFO trace level for the current file.
#define INFO                4

/// Maximum number of images in slideshow.
#define MAXIMAGES           10

/// Base address for storing BMP files.
#define FIRSTIMAGEADDRESS   (IMAGE_BUF_BASE_ADDR + 0x00200000)

/// Missing RTTC0 definition.
#if !defined(AT91C_BASE_RTTC) && defined(AT91C_BASE_RTTC0)
    #define AT91C_BASE_RTTC    AT91C_BASE_RTTC0
#endif

//------------------------------------------------------------------------------
//         Prototypes
//------------------------------------------------------------------------------

static void ReceiveBmpHeader();
static void ReceiveBmpData(unsigned int size);

//------------------------------------------------------------------------------
//         Internal constants
//------------------------------------------------------------------------------

/// Primary display buffer.
unsigned char *primaryBuffer = (unsigned char *) (IMAGE_BUF_BASE_ADDR + 0x00010000);

/// Back buffer (for double-buffering).
unsigned char *backBuffer = (unsigned char *) (IMAGE_BUF_BASE_ADDR + 0x00100000);

/// Number of received images (for slideshow).
unsigned char numImages;

/// Address of BMP files to display.
unsigned int images[MAXIMAGES];

/// Size of BMP files;
unsigned int imageSizes[MAXIMAGES];

//------------------------------------------------------------------------------
//         VBus monitoring (optional)
//------------------------------------------------------------------------------
#if defined(PIN_USB_VBUS)

#define VBUS_CONFIGURE()  VBus_Configure()

/// VBus pin instance.
static const Pin pinVbus = PIN_USB_VBUS;

//------------------------------------------------------------------------------
/// Handles interrupts coming from PIO controllers.
//------------------------------------------------------------------------------
static void ISR_Vbus(const Pin *pPin)
{
    // Check current level on VBus
    if (PIO_Get(&pinVbus)) {

        TRACE_INFO("VBUS conn\n\r");
        USBD_Connect();
    }
    else {

        TRACE_INFO("VBUS discon\n\r");
        USBD_Disconnect();
    }
}

//------------------------------------------------------------------------------
/// Configures the VBus pin to trigger an interrupt when the level on that pin
/// changes.
//------------------------------------------------------------------------------
static void VBus_Configure( void )
{
    TRACE_INFO("VBus configuration\n\r");

    // Configure PIO
    PIO_Configure(&pinVbus, 1);
    PIO_ConfigureIt(&pinVbus, ISR_Vbus);
    PIO_EnableIt(&pinVbus);

    // Check current level on VBus
    if (PIO_Get(&pinVbus)) {

        // if VBUS present, force the connect
        TRACE_INFO("conn\n\r");
        USBD_Connect();
    }
    else {
        USBD_Disconnect();
    }           
}

#else
    #define VBUS_CONFIGURE()    USBD_Connect()
#endif //#if defined(PIN_USB_VBUS)

//------------------------------------------------------------------------------
//         Internal functions
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
/// Configures the PIO needed by the application.
//------------------------------------------------------------------------------
static void ConfigurePins()
{
#if defined(PINS_SDRAM)
    static const Pin pins[] = {PINS_LCD, PINS_SDRAM};
#elif defined(PINS_DDRAM)
     static const Pin pins[] = {PINS_LCD, PINS_DDRAM};
#else
    #error no PINS_SDRAM or PINS_DDRAM
#endif

    PIO_Configure(pins, PIO_LISTSIZE(pins));
}

//------------------------------------------------------------------------------
/// Initializes the LCD controller with the board parameters.
//------------------------------------------------------------------------------
void InitializeLcd()
{
    // Enable peripheral clock
    AT91C_BASE_PMC->PMC_PCER = 1 << AT91C_ID_LCDC;

#if defined(at91sam9g10)||defined(at91sam9261)
    AT91C_BASE_PMC->PMC_SCER = AT91C_PMC_HCK1;
#endif

    // Disable the LCD and the DMA
    LCD_DisableDma();
    LCD_Disable(0);

    // Configure the LCD controller
    LCD_SetPixelClock(BOARD_MCK, BOARD_LCD_PIXELCLOCK);
    LCD_SetDisplayType(BOARD_LCD_DISPLAYTYPE);
    LCD_SetScanMode(AT91C_LCDC_SCANMOD_SINGLESCAN);
    LCD_SetBitsPerPixel(BOARD_LCD_BPP);
    LCD_SetPolarities(BOARD_LCD_POLARITY_INVVD,
                      BOARD_LCD_POLARITY_INVFRAME,
                      BOARD_LCD_POLARITY_INVLINE,
                      BOARD_LCD_POLARITY_INVCLK,
                      BOARD_LCD_POLARITY_INVDVAL);
    LCD_SetClockMode(BOARD_LCD_CLOCKMODE);
    LCD_SetMemoryFormat((unsigned int) AT91C_LCDC_MEMOR_LITTLEIND);
    LCD_SetSize(BOARD_LCD_WIDTH, BOARD_LCD_HEIGHT);

    // Configure timings
    LCD_SetVerticalTimings(BOARD_LCD_TIMING_VFP,
                           BOARD_LCD_TIMING_VBP,
                           BOARD_LCD_TIMING_VPW,
                           BOARD_LCD_TIMING_VHDLY);
    LCD_SetHorizontalTimings(BOARD_LCD_TIMING_HBP,
                             BOARD_LCD_TIMING_HPW,
                             BOARD_LCD_TIMING_HFP);

    // Configure contrast (TODO functions)
    LCD_SetContrastPrescaler(AT91C_LCDC_PS_NOTDIVIDED);
    LCD_SetContrastPolarity(AT91C_LCDC_POL_POSITIVEPULSE);
    LCD_SetContrastValue(0x80);
    LCD_EnableContrast();

    // Configure DMA
    LCD_SetFrameSize(BOARD_LCD_FRAMESIZE);
    LCD_SetBurstLength(4);

    // Set frame buffer
    LCD_SetFrameBufferAddress(primaryBuffer);

    // Enable DMA and LCD
    LCD_EnableDma();
    LCD_Enable(0x0C);
}

//------------------------------------------------------------------------------
/// Callback invoked whenever part of the BMP header has been received. Note
/// that part of the actual image data can be received along the header.
/// \param image  Index of image being received.
/// \param status  Operation result code.
/// \param received  Number of bytes received.
/// \param remaining  Number of bytes discarded or not received.
//------------------------------------------------------------------------------
static void BmpHeaderReceived(
    unsigned int image,
    unsigned char status,
    unsigned int received,
    unsigned int remaining)
{
    imageSizes[image] += received;

    // Check if a full header has been received
    if (imageSizes[image] >= sizeof(struct BMPHeader)) {

        TRACE_INFO("BMP header received.\n\r");

        // Check header validity
        if (!BMP_IsValid((void *) images[image])) {

            TRACE_WARNING( "BMP image is not valid\n\r");

            // Restart transfer
            imageSizes[image] = 0;
            ReceiveBmpHeader(image);
        }
        else {
        
            ReceiveBmpData(image);
        }
    }
    // Otherwise, restart a read operation
    else {

        ReceiveBmpHeader(image);
    }
}

//------------------------------------------------------------------------------
/// Starts the reception of the BMP header data on the USB.
/// \param image  Index of image being received.
//------------------------------------------------------------------------------
static void ReceiveBmpHeader(unsigned int image)
{
    unsigned char status;

    // Start read
    do {

        status = CDCDSerialDriver_Read(
                    (unsigned char *) (images[image] + imageSizes[image]),
                    BOARD_USB_ENDPOINTS_MAXPACKETSIZE(CDCDSerialDriverDescriptors_DATAOUT),
                    (TransferCallback) BmpHeaderReceived,
                    (void *) image);
    }
    while (status != USBD_STATUS_SUCCESS);

    TRACE_INFO("Ready to receive BMP file #%u.\n\r", image);
}

//------------------------------------------------------------------------------
/// Callback invoked when some BMP image data has been received.
/// \param image  Index of image being received.
/// \param status  Operation result code.
/// \param received  Number of image bytes received.
/// \param remaining  Number of bytes not received or discarded.
//------------------------------------------------------------------------------
static void BmpDataReceived(
    unsigned int image,
    unsigned char status,
    unsigned int received,
    unsigned int remaining)
{
    imageSizes[image] += received;

    // Check if image has been completely received
    if (imageSizes[image] == BMP_GetFileSize((void *) images[image])) {

        TRACE_INFO("BMP image #%u received.\n\r", image);

        // Start new transfer if there are images remaining
        if (numImages < MAXIMAGES) {

            images[image+1] = images[image] + imageSizes[image];
            numImages++;
            ReceiveBmpHeader(numImages);
        }
    }
    // Otherwise, restart a read operation
    else {

        ReceiveBmpData(image);
    }
}

//------------------------------------------------------------------------------
/// Starts the reception of the BMP image data on the USB.
/// \param image  Index of image being received.
//------------------------------------------------------------------------------
static void ReceiveBmpData(unsigned int image)
{
    unsigned char status;

    // Start read
    do {

        status = CDCDSerialDriver_Read(
                    (unsigned char *) (images[image] + imageSizes[image]),
                    BMP_GetFileSize((void *) images[image]) - imageSizes[image],
                    (TransferCallback) BmpDataReceived,
                    (void *) image);
    }
    while (status != USBD_STATUS_SUCCESS);
}

//------------------------------------------------------------------------------
/// Interrupt handler for RTT interrupts.
//------------------------------------------------------------------------------
void RTT_IrqHandler()
{
    static unsigned int currentImage = 0;
    volatile unsigned int status;
    unsigned char *tmp;

    status = RTT_GetStatus(AT91C_BASE_RTTC);

    // Check if RTT has been incremented
    if ((status & AT91C_RTTC_RTTINC) != 0) {

        // If there are no images to display, return
        if (numImages == 0) {

            return;
        }

        // Display back buffer (previously decoded image is inside it)
        LCD_SetFrameBufferAddress(backBuffer);
        tmp = backBuffer;
        backBuffer = primaryBuffer;
        primaryBuffer = tmp;

        // Change current image
        currentImage++;
        if (currentImage >= numImages) {

            currentImage -= numImages;
        }

        // Decode new image
        BMP_Decode((void *) images[currentImage],
                   backBuffer,
                   //BOARD_LCD_WIDTH,
                   240, //use a fixed width to meet pic resolution under project dir
                   //BOARD_LCD_HEIGHT,
                   320, //use a fixed width to meet pic resolution under project dir
                   24);
    }
}

//------------------------------------------------------------------------------
/// Main function
//------------------------------------------------------------------------------
int main()
{   
    unsigned int i;

    TRACE_CONFIGURE(DBGU_STANDARD, 115200, BOARD_MCK);
    printf("-- LCD Slideshow Project %s --\n\r", SOFTPACK_VERSION);
    printf("-- %s\n\r", BOARD_NAME);
    printf("-- Compiled: %s %s --\n\r", __DATE__, __TIME__);

    // If they are present, configure Vbus & Wake-up pins
    PIO_InitializeInterrupts(0);

    // Configure pins
    ConfigurePins();

#if !defined(sdram) && defined(PINS_SDRAM)
    // Initialize SDRAM
    BOARD_ConfigureSdram(BOARD_SDRAM_BUSWIDTH);
#endif
    
#if !defined(ddram) && defined(PINS_DDRAM)
    //configure DDRAM for use
    BOARD_ConfigureDdram(0, BOARD_DDRAM_BUSWIDTH);
#endif

    // Initialize LCD
    memset(primaryBuffer, 0, BOARD_LCD_FRAMESIZE * 4);
    memset(backBuffer, 0, BOARD_LCD_FRAMESIZE * 4);
    InitializeLcd();

    // Reset images
    numImages = 0;
    for (i=0; i < MAXIMAGES; i++) {

        images[i] = 0;
        imageSizes[i] = 0;
    }
    images[0] = FIRSTIMAGEADDRESS;

    // Configure RTT for a 2s tick
    RTT_SetPrescaler(AT91C_BASE_RTTC, 0);
    i = RTT_GetTime(AT91C_BASE_RTTC);
    while(i == RTT_GetTime(AT91C_BASE_RTTC));
    IRQ_ConfigureIT(AT91C_ID_SYS, 0, RTT_IrqHandler);
    IRQ_EnableIT(AT91C_ID_SYS);
    RTT_EnableIT(AT91C_BASE_RTTC, AT91C_RTTC_RTTINCIEN);

    // Initialize the serial driver
    CDCDSerialDriver_Initialize();

    // connect if needed
    VBUS_CONFIGURE();

    while (USBD_GetState() < USBD_STATE_CONFIGURED);

    // Infinite loop
    while (1) {

        // Start receiving data on the USB
        if (numImages < MAXIMAGES) {
        
            ReceiveBmpHeader(numImages);
        }
    }
}

