/* ----------------------------------------------------------------------------
 *         ATMEL Microcontroller Software Support 
 * ----------------------------------------------------------------------------
 * Copyright (c) 2008, Atmel Corporation
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the disclaimer below.
 *
 * Atmel's name may not be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * DISCLAIMER: THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * ----------------------------------------------------------------------------
 */

//------------------------------------------------------------------------------
/// \dir "Basic LCD Project"
///
/// !!!Purpose
///
/// This application displays two preloaded images on the board LCD, alternating 
/// between each image every other second.
/// 
/// !See
/// - lcd: LCD controller driver
/// - rtt: Real-time timer driver
///
/// !!!Requirements
///
/// This package can be used with all Atmel evaluation kits that have LCD
/// interface, the package runs at SDRAM or SRAM.
///
/// !!!Description
///
/// When launched, this example will start displaying two images alternatively, 
/// changing between them every two seconds. The images must be loaded in SDRAM 
/// before the program execution, at offsets 0x100000 and 0x200000, respectively.
///
/// The image files must only contain raw RGB data, as no file format conversion 
/// is done. Two already processed images, named image1_rgb.raw and
/// image2_rgb.raw, are provided in the project folder. 
/// You can use the <a href="http://www.imagemagick.org/">ImageMagik</a> software 
/// to convert BMP to raw data.
///
/// !!!Usage
///
/// -# Compile the application. 
/// -# #Using SAM-BA#, enable the SDRAM of the chip and download the two images 
/// provided, at offsets 0x100000 and 0x200000, respectively. Please refer to the 
/// <a href="http://www.atmel.com/dyn/resources/prod_documents/doc6132.pdf">
/// SAM-BA User Guide</a>
/// for more information about that step. 
/// -# Optionally, connect the DBGU port of the evaluation board to the computer 
/// and open it in a terminal. Debug information generated by the application 
/// will be visibled that way. 
///     - Settings: 115200 bauds, 8 bits, 1 stop bit, no parity, no flow control. 
/// -# #Using SAM-BA#, download the program inside the evaluation board and run 
/// -# The two downloaded images should appear alternatively on the LCD. 
/// it. In addition, the following message should appear on the DBGU: 
///     \code
///     -- Basic LCD Project xxx -- 
///     -- AT91xxxxxx-xx
///     -- Compiled: xxx xx xxxx xx:xx:xx --
///     \endcode
///
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
/// \unit
///
/// !Purpose
///
/// This file contains all the specific code for the basic-lcd-project
///
/// !Contents
/// The code can be roughly broken down as follows:
///    - Configuration functions
///    - Initialization functions
///    - The main function, which implements the program behavior 
///       - Configure pins
///       - Initialize LCD
///       - Start displaying two images alternatively
///
/// Please refer to the list of functions in the #Overview# tab of this unit
/// for more detailed information.
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//         Headers
//------------------------------------------------------------------------------

#include <board.h>
#include <board_memories.h>
#include <pio/pio.h>
#include <lcd/lcd.h>
#include <rtt/rtt.h>
#include <irq/irq.h>
#include <utility/trace.h>

#include <string.h>
#include <stdio.h>

//------------------------------------------------------------------------------
//         Internal constants
//------------------------------------------------------------------------------

/// Addresses of the two image buffers
#if defined(PINS_DDRAM)
unsigned char *images[2] = {
    (unsigned char *) (AT91C_DDR2 + 0x00100000),
    (unsigned char *) (AT91C_DDR2 + 0x00200000)
};
#elif defined(PINS_SDRAM)
unsigned char *images[2] = {
    (unsigned char *) (AT91C_EBI_SDRAM + 0x00100000),
    (unsigned char *) (AT91C_EBI_SDRAM + 0x00200000)
};
#else
    #error Not define PINS_SDRAM or PINS_DDRAM
#endif

//------------------------------------------------------------------------------
//         Internal functions
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
/// Configures the PIO needed by the application.
//------------------------------------------------------------------------------
static void ConfigurePins()
{
    static const Pin pins[] = {PINS_LCD};
    PIO_Configure(pins, PIO_LISTSIZE(pins));
}

//------------------------------------------------------------------------------
/// Initializes the LCD controller with the board parameters.
//------------------------------------------------------------------------------
void InitializeLcd()
{
    // Enable peripheral clock
    AT91C_BASE_PMC->PMC_PCER = 1 << AT91C_ID_LCDC;

#if defined(at91sam9g10)||defined(at91sam9261)
    AT91C_BASE_PMC->PMC_SCER = AT91C_PMC_HCK1;
#endif

    // Disable the LCD and the DMA
    LCD_DisableDma();
    LCD_Disable(0);

    // Configure the LCD controller
    LCD_SetPixelClock(BOARD_MCK, BOARD_LCD_PIXELCLOCK);
    LCD_SetDisplayType(BOARD_LCD_DISPLAYTYPE);
    LCD_SetScanMode(AT91C_LCDC_SCANMOD_SINGLESCAN);
    LCD_SetBitsPerPixel(BOARD_LCD_BPP);
    LCD_SetPolarities(BOARD_LCD_POLARITY_INVVD,
                      BOARD_LCD_POLARITY_INVFRAME,
                      BOARD_LCD_POLARITY_INVLINE,
                      BOARD_LCD_POLARITY_INVCLK,
                      BOARD_LCD_POLARITY_INVDVAL);
    LCD_SetClockMode(BOARD_LCD_CLOCKMODE);
    LCD_SetMemoryFormat((unsigned int) AT91C_LCDC_MEMOR_LITTLEIND);
    LCD_SetSize(BOARD_LCD_WIDTH, BOARD_LCD_HEIGHT);

    // Configure timings
    LCD_SetVerticalTimings(BOARD_LCD_TIMING_VFP,
                           BOARD_LCD_TIMING_VBP,
                           BOARD_LCD_TIMING_VPW,
                           BOARD_LCD_TIMING_VHDLY);
    LCD_SetHorizontalTimings(BOARD_LCD_TIMING_HBP,
                             BOARD_LCD_TIMING_HPW,
                             BOARD_LCD_TIMING_HFP);

    // Configure contrast (TODO functions)
    LCD_SetContrastPrescaler(AT91C_LCDC_PS_NOTDIVIDED);
    LCD_SetContrastPolarity(AT91C_LCDC_POL_POSITIVEPULSE);
    LCD_SetContrastValue(0x80);
    LCD_EnableContrast();

    // Configure DMA
    LCD_SetFrameSize(BOARD_LCD_FRAMESIZE);
    LCD_SetBurstLength(4);

    // Set frame buffer
    LCD_SetFrameBufferAddress(images[0]);

    // Enable DMA and LCD
    LCD_EnableDma();
    LCD_Enable(0x0C);
}

//------------------------------------------------------------------------------
/// Main function
//------------------------------------------------------------------------------
int main()
{   
    unsigned int time;
    unsigned int nextImage = 0;

    TRACE_CONFIGURE(DBGU_STANDARD, 115200, BOARD_MCK);
    printf("-- Basic LCD Project %s --\n\r", SOFTPACK_VERSION);
    printf("-- %s\n\r", BOARD_NAME);
    printf("-- Compiled: %s %s --\n\r", __DATE__, __TIME__);

#if !defined(sdram) && defined(PINS_SDRAM)
    //configure SDRAM for use
    BOARD_ConfigureSdram(BOARD_SDRAM_BUSWIDTH);
#endif

    
#if !defined(ddram) && defined(PINS_DDRAM)
    //configure DDRAM for use
    BOARD_ConfigureDdram(0, BOARD_DDRAM_BUSWIDTH);
#endif
    
#if defined(BOARD_LCD_RGB565)
    unsigned int i, image;
    unsigned char r, g, b;

    // RGB 565 fix
    for (image = 0; image < 2; image++) {
    
        for (i = 0; i < (240 * 320 * 3); i += 3) {
    
            r = images[image][i];
            g = images[image][i+1];
            b = images[image][i+2];
    
            // Interlacing
            r = ((r << 1) & 0xF0) | ((g & 0x80) >> 4) | ((r & 0x80) >> 5);
            g = (g << 1) & 0xF8;
            b = b & 0xF8;
    
            // R & B inversion
            images[image][i+2] = r;
            images[image][i+1] = g;
            images[image][i] = b;
        }
    }
#elif defined (BOARD_LCD_BGR565)
    unsigned int i, image;
    unsigned char r, g, b;

    // RGB 565 fix
    for (image = 0; image < 2; image++) {
    
        for (i = 0; i < (240 * 320 * 3); i += 3) {
    
            r = images[image][i];
            g = images[image][i+1];
            b = images[image][i+2];
    
            // R & B inversion
            images[image][i+2] = r;
            images[image][i+1] = g;
            images[image][i] = b;
        }
    }
#endif //#if defined(BOARD_LCD_RGB565)

    // Configure pins
    ConfigurePins();

    // Initialize LCD
    InitializeLcd();

    // Configure RTT for a 2s tick
    RTT_SetPrescaler(AT91C_BASE_RTTC, 0);

    // Infinite loop
    time = RTT_GetTime(AT91C_BASE_RTTC);
    while (1) {

        // Wait next second
        while (time == RTT_GetTime(AT91C_BASE_RTTC));
        time = RTT_GetTime(AT91C_BASE_RTTC);

        // Display image
        LCD_SetFrameBufferAddress(images[nextImage]);
        nextImage = (nextImage + 1) % 2;
    }

    return 0;
}

